---
- name: Setup RabbitMQ
  hosts: rabbitmq,&VM
  vars:
    pile_of_targets:
    - name: 'socat'     # rabbitmq-server
      type: 'repo'

    - name: 'logrotate' # rabbitmq-server
      type: 'repo'

    - name: 'erlang'    # rabbitmq-server
      type: 'rpm'
      pkg: 'https://github.com/rabbitmq/erlang-rpm/releases/download/v23.3.4.10/erlang-23.3.4.10-1.el7.x86_64.rpm'

    - name: 'rabbitmq-server'
      type: 'key'
      key: 'https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc'

    - name: 'rabbitmq-server'
      type: 'rpm'
      pkg: 'https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.9.13/rabbitmq-server-3.9.13-1.el7.noarch.rpm'

    - name: 'node_exporter'
      type: 'tar'
      src: 'https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz'
      creates: 'node_exporter-1.3.1.linux-amd64'


  tasks:

  - name: Create working directory
    ansible.builtin.file:
      path: "/tmp/my_ansible_cwd"
      state: directory
    register: _my_cwd

  - name: Install targets
    include_tasks: roles/common/tasks/targets-install.yml
    loop: "{{ pile_of_targets }}"
    loop_control:
      loop_var: target
